services:
  - type: web
    name: avroai
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000

